language: python
python:
  - "2.7"
# command to install dependencies
install: 
  - "virtualenv --no-site-packages env"
  - "env/bin/pip install flake8 --use-mirrors"
  - "env/bin/pip install -r requirements.txt --use-mirrors"
  - "env/bin/pip install -r test-requirements.txt --use-mirrors"
  - "env/bin/python setup.py develop"
before_script:
  #- "flake8 situation --ignore=E501,W291,W293"
  - "wget https://commondatastorage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.3.zip"
  - "unzip -q google_appengine_1.9.3.zip"
  - 'echo "$PWD/google_appengine" >> env/lib/python2.7/site-packages/gae.pth'
  - 'echo "import dev_appserver; dev_appserver.fix_sys_path()" >> env/lib/python2.7/site-packages/gae.pth'
# command to run tests
script: "env/bin/nosetests -sv"
